disabled_rules:
  - trailing_whitespace
opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping
  - explicit_init
  - explicit_acl
  - closure_spacing
  - overridden_super_call
  - redundant_nil_coalescing
  - private_outlet
  - nimble_operator
  - attributes
  - operator_usage_whitespace
  - closure_end_indentation
  - first_where
  - sorted_first_last
  - contains_over_first_not_nil
  - fallthrough
  - unused_optional_binding
  - multiline_parameters
  - multiline_function_chains
  - multiline_arguments

excluded:
  - build
  - Pods
  - .build

line_length:
  warning: 120
  error: 200
  ignores_comments: true

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - x
    - y
    - z

reporter: "xcode"
